# Generated by Django 5.1.6 on 2025-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiTailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('shoulders', models.FloatField(blank=True, null=True)),
                ('arm_length', models.FloatField(blank=True, null=True)),
                ('fabric', models.CharField(max_length=50)),
                ('dress_type', models.CharField(max_length=50)),
            ],
        ),
    ]
