# Generated by Django 5.1.6 on 2025-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiTailor', '0002_generateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('chest', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('hips', models.IntegerField()),
                ('shoulders', models.IntegerField()),
                ('arm_length', models.IntegerField()),
                ('fabric', models.CharField(max_length=50)),
                ('dress_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GenerateImage',
        ),
    ]
